ARG ARCH=amd64
FROM go-ide:${ARCH}-latest

ARG ARCH=amd64
ARG ARCH2=x86_64
ARG ARCH3

ARG TERRAFORM_VERSION=0.15.5
USER root

RUN apt install -y apt-transport-https jsonnet

#install terraform
RUN wget --progress=dot:mega https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_${ARCH3}.zip

RUN \
	# Unzip
	unzip terraform_${TERRAFORM_VERSION}_linux_${ARCH3}.zip && \
	# Move to local bin
	mv terraform /usr/local/bin/ && \
	# Make it executable
	chmod +x /usr/local/bin/terraform && \
	# Check that it's installed
	terraform --version

#install aws cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-${ARCH2}.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

#install kubectl
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list && \
    apt-get update && apt-get install -y kubectl && \
    echo "source <(kubectl completion zsh)" >> /home/dev/.zshrc

#install helm
RUN curl https://baltocdn.com/helm/signing.asc | apt-key add - && \
    echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list && \
    apt-get update && apt-get install helm && \
    echo "source <(helm completion zsh)" >> /home/dev/.zshrc

#install istioctl
RUN curl -sL https://istio.io/downloadIstioctl | TARGET_ARCH=${ARCH2} sh - && \
    mv $HOME/.istioctl/bin/istioctl /usr/bin/istioctl

#install argo
RUN curl -sLO https://github.com/argoproj/argo/releases/download/v3.0.3/argo-linux-${ARCH3}.gz && \
    gunzip argo-linux-${ARCH3}.gz && \
    chmod +x argo-linux-${ARCH3} && \
    mv ./argo-linux-${ARCH3} /usr/bin/argo && \
    mkdir $HOME/.oh-my-zsh/custom/plugins/argo && \
    argo completion zsh > $HOME/.oh-my-zsh/custom/plugins/argo/argo.plugin.zsh && \
    echo "compdef _argo argo" >> /home/dev/.zshrc

#install argocd
ARG ARGOCD_VERSION=v2.0.1
RUN if [ "$ARCH" = "amd64" ] ; then curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/${ARGOCD_VERSION}/argocd-linux-${ARCH3} && \
    chmod +x /usr/local/bin/argocd && \
    mkdir $HOME/.oh-my-zsh/custom/plugins/argocd && \
    argocd completion zsh > $HOME/.oh-my-zsh/custom/plugins/argocd/argocd.plugin.zsh && \
    echo "compdef _argocd argocd" >> /home/dev/.zshrc ; fi

#install kubeseal
RUN wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/kubeseal-linux-${ARCH3} -O kubeseal && \
    install -m 755 kubeseal /usr/local/bin/kubeseal

RUN rm /home/dev/*.zip
COPY aliases /home/dev/.aliases
RUN echo "source $HOME/.aliases" >> /home/dev/.zshrc && \
    sed -i 's/plugins=(git)/plugins=(git argocd argo)/g' ~/.zshrc

USER dev
CMD "exec zsh"

